Repository grc-iit/ChronoLog, pull requests merged in 2025-01, with the labels that each got.

#237 236 conf manager segfault
  chrono_common/ConfigurationManager.h
  default_conf.json.in
Labels: bug

#243 201 chronoplayer registration with Visor
  ChronoVisor/include/KeeperRegistry.h
  ChronoVisor/include/KeeperRegistryService.h
  ChronoVisor/src/KeeperRegistry.cpp
  chrono_common/PlayerRegistrationMsg.h
Labels: ChronoPlayer

#245 207 add chronoplayer component to local deployment scripts
  deploy/local_single_user_deploy.sh
Labels: Testing & Deployment

#244 203 range query hdf5 reader
  ChronoGrapher/CMakeLists.txt
  ChronoPlayer/ArchiveReadingAgent.h
  ChronoPlayer/CMakeLists.txt
  ChronoPlayer/HDF5ArchiveReadingAgent.cpp
  ChronoPlayer/HDF5ArchiveReadingAgent.h
  ChronoPlayer/HDF5ArchiveReadingAgentTest.cpp
  chrono_common/StoryChunkWriter.cpp
  chrono_common/StoryChunkWriter.h
Labels: high priority, ChronoPlayer
