Repository grc-iit/ChronoLog, pull requests merged in 2025-07, with the labels that each got.

#342 253 python bindings for replay story API
  CMakeLists.txt
  python_client/py_chronolog_client.cpp
  python_client/reader_client.py
  python_client/writer_client.py
Labels: ChronoLogClient

#347 Fix Player crashing on only one archive file
  ChronoPlayer/HDF5ArchiveReadingAgent.cpp
Labels: bug, ChronoPlayer

#359 320 add a reader simple example code
  Client/examples/CMakeLists.txt
  Client/examples/client_lib_reader_example.cpp
Labels: ChronoLogClient

#363 Set Player's recording group id properly
  deploy/single_user_deploy.sh
Labels: bug, Testing & Deployment

#349 332 configurable datastore parameters
  ChronoGrapher/ChronoGrapher.cpp
  ChronoGrapher/GrapherDataStore.cpp
  ChronoGrapher/GrapherDataStore.h
  ChronoKeeper/ChronoKeeperInstance.cpp
  ChronoKeeper/KeeperDataStore.cpp
  ChronoKeeper/KeeperDataStore.h
  ChronoKeeper/StoryPipeline.cpp
  ChronoKeeper/StoryPipeline.h
  ChronoPlayer/ChronoPlayer.cpp
  ChronoPlayer/HDF5ArchiveReadingAgentTest.cpp
  ChronoVisor/include/KeeperRegistry.h
  ChronoVisor/include/VisorClientPortal.h
  ChronoVisor/src/KeeperRegistry.cpp
  ChronoVisor/src/VisorClientPortal.cpp
  ChronoVisor/src/chronovisor_instance.cpp
  chrono_common/ConfigurationManager.cpp
  chrono_common/ConfigurationManager.h
  chrono_common/StoryPipeline.cpp
  chrono_common/StoryPipeline.h
  default_conf.json.in
  test/integration/Keeper-Grapher/extract_test.cpp
  test/integration/Keeper-Grapher/ingest_test.cpp
Labels: enhancement
